# Generated by Django 4.2.15 on 2024-10-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dynamic_fields',
            field=models.JSONField(default=dict),
        ),
    ]
