# Generated by Django 4.2.15 on 2024-10-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_dynamic_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='dynamic_fields',
        ),
    ]
